site_name: My Docs

repo_name: Github Repository
repo_url: https://github.com/svavarkonn/MkDocs

theme:
  name: material
  logo: images/SK_logo.svg
  favicon: images/SK_logo.svg
  features:
    - content.code.annotate
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
  custom_dir: docs/overrides


  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
      primary: indigo
      accent: deep orange
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline 
        name: Switch to light mode

      primary: indigo
      accent: amber
markdown_extensions:

  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - admonition
  - attr_list
  - md_in_html
  
nav:
  - Home: index.md
  - Setup: setup.md
  - Seeed Studio: seeed.md
  - Code tests:  code.md
  - Robot notes: robot_spiral_1.md
use_directory_urls: false

copyright: Copyright &copy; 2023 Svavar Konráðsson